# Generated by Django 3.1.3 on 2020-11-05 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
